### ISSUE TITLE
req: Details of how you created the script-detection

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken-models#2]
Peace Be Upon you,
Can you share the details of how you created the Script-Detection model.
I am currently working on creating a Font Identifier model, it would be helpful.
Waiting for your reply

**Comment by mittagessen** [comment]
Don't use that one for now, it only recognizes Unicode blocks. 

For a new model that is training right now I've combined [ISO 15924](http://unicode.org/iso15924/iso15924-codes.html) (script codes) with the [Unicode script property](http://www.unicode.org/reports/tr24/) and mapped those into the private use area of Unicode by just adding the script number to 0xF0000 (start of PUA). The training data (~17500 lines) is just the training data for every model I could find where each character is replaced by their respective script identifier. Training will take considerably longer than for recognition models (20 epochs/300000 iterations and it is still improving).
